In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
fraudtest_data = pd.read_csv('fraudTest.csv')
fraudtest_data.head()

Unnamed: 0 trans_date_trans_time        cc_num  \
0           0   2020-06-21 12:14:25  2.291164e+15   
1           1   2020-06-21 12:14:33  3.573030e+15   
2           2   2020-06-21 12:14:53  3.598215e+15   
3           3   2020-06-21 12:15:15  3.591920e+15   
4           4   2020-06-21 12:15:17  3.526826e+15   

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff   
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne   
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley   
3                     fraud_Haley Group        misc_pos  60.05   Brian   
4                 fraud_Johnston-Casper          travel   3.19  Nathan   

       last gender                       street  ...      lat      long  \
0   Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1  Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2     Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3  Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4    Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   

   city_pop                     job         dob  \
0  333497.0     Mechanical engineer  1968-03-19   
1     302.0  Sales professional, IT  1990-01-17   
2   34496.0       Librarian, public  1970-10-21   
3   54767.0            Set designer  1987-07-25   
4    1126.0      Furniture designer  1955-07-06   

                          trans_num     unix_time  merch_lat  merch_long  \
0  2da90c7d74bd46a0caf3777415b3ebd3  1.371817e+09  33.986391  -81.200714   
1  324cc204407e99f51b0d6ca0055005e7  1.371817e+09  39.450498 -109.960431   
2  c81755dbbbea9d5c77f094348a7579be  1.371817e+09  40.495810  -74.196111   
3  2159175b9efe66dc301f149d3d5abf8c  1.371817e+09  28.812398  -80.883061   
4  57ff021bd3f328f8738bb535c302a31b  1.371817e+09  44.959148  -85.884734   

   is_fraud  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 23 columns]

In [2]:
fraudtrain_data = pd.read_csv('fraudTrain.csv')
fraudtrain_data.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095   
1           1   2019-01-01 00:00:44      630423337322   
2           2   2019-01-01 00:00:51    38859492057661   
3           3   2019-01-01 00:01:16  3534093764340240   
4           4   2019-01-01 00:03:06   375534208663984   

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer   
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie   
2                fraud_Lind-Buckridge  entertainment  220.11     Edward   
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy   
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler   

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781   
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105   
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620   
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138   
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629   

   city_pop                                job         dob  \
0      3495          Psychologist, counselling  1988-03-09   
1       149  Special educational needs teacher  1978-06-21   
2      4154        Nature conservation officer  1962-01-19   
3      1939                    Patent attorney  1967-01-12   
4        99     Dance movement psychotherapist  1986-03-28   

                          trans_num   unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1325376018  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1325376044  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704 -112.154481   
3  6b849c168bdad6f867558c3793159a81  1325376076  47.034331 -112.561071   
4  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999  -78.632459   

   is_fraud  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 23 columns]

In [4]:
fraudtrain_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23367 entries, 0 to 23366
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Unnamed: 0             23367 non-null  int64  
 1   trans_date_trans_time  23367 non-null  object 
 2   cc_num                 23367 non-null  int64  
 3   merchant               23367 non-null  object 
 4   category               23367 non-null  object 
 5   amt                    23367 non-null  float64
 6   first                  23367 non-null  object 
 7   last                   23367 non-null  object 
 8   gender                 23367 non-null  object 
 9   street                 23367 non-null  object 
 10  city                   23367 non-null  object 
 11  state                  23367 non-null  object 
 12  zip                    23367 non-null  int64  
 13  lat                    23367 non-null  float64
 14  long                   23367 non-null  float64
 15  ci

In [5]:
fraudtest_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31124 entries, 0 to 31123
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Unnamed: 0             31124 non-null  int64  
 1   trans_date_trans_time  31124 non-null  object 
 2   cc_num                 31123 non-null  float64
 3   merchant               31123 non-null  object 
 4   category               31123 non-null  object 
 5   amt                    31123 non-null  float64
 6   first                  31123 non-null  object 
 7   last                   31123 non-null  object 
 8   gender                 31123 non-null  object 
 9   street                 31123 non-null  object 
 10  city                   31123 non-null  object 
 11  state                  31123 non-null  object 
 12  zip                    31123 non-null  float64
 13  lat                    31123 non-null  float64
 14  long                   31123 non-null  float64
 15  ci

In [6]:
fd = pd.concat([fraudtrain_data, fraudtest_data])
fd.head()

Unnamed: 0 trans_date_trans_time        cc_num  \
0           0   2019-01-01 00:00:18  2.703186e+15   
1           1   2019-01-01 00:00:44  6.304233e+11   
2           2   2019-01-01 00:00:51  3.885949e+13   
3           3   2019-01-01 00:01:16  3.534094e+15   
4           4   2019-01-01 00:03:06  3.755342e+14   

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer   
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie   
2                fraud_Lind-Buckridge  entertainment  220.11     Edward   
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy   
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler   

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781   
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105   
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620   
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138   
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629   

   city_pop                                job         dob  \
0    3495.0          Psychologist, counselling  1988-03-09   
1     149.0  Special educational needs teacher  1978-06-21   
2    4154.0        Nature conservation officer  1962-01-19   
3    1939.0                    Patent attorney  1967-01-12   
4      99.0     Dance movement psychotherapist  1986-03-28   

                          trans_num     unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1.325376e+09  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1.325376e+09  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1.325376e+09  43.150704 -112.154481   
3  6b849c168bdad6f867558c3793159a81  1.325376e+09  47.034331 -112.561071   
4  a41d7549acf90789359a9aa5346dcb46  1.325376e+09  38.674999  -78.632459   

   is_fraud  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 23 columns]

In [7]:
fd.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   1
merchant                 1
category                 1
amt                      1
first                    1
last                     1
gender                   1
street                   1
city                     1
state                    1
zip                      1
lat                      1
long                     1
city_pop                 1
job                      1
dob                      1
trans_num                1
unix_time                1
merch_lat                1
merch_long               1
is_fraud                 2
dtype: int64

In [8]:
fd.shape[0]

54491

In [9]:
fd.fillna(0, inplace=True)
fd.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [10]:
fd.drop(columns=['Unnamed: 0', 'gender', 'street', 'job', 'unix_time','trans_num','merchant','zip'], inplace=True)
fd.head()

trans_date_trans_time        cc_num       category     amt      first  \
0   2019-01-01 00:00:18  2.703186e+15       misc_net    4.97   Jennifer   
1   2019-01-01 00:00:44  6.304233e+11    grocery_pos  107.23  Stephanie   
2   2019-01-01 00:00:51  3.885949e+13  entertainment  220.11     Edward   
3   2019-01-01 00:01:16  3.534094e+15  gas_transport   45.00     Jeremy   
4   2019-01-01 00:03:06  3.755342e+14       misc_pos   41.96      Tyler   

      last            city state      lat      long  city_pop         dob  \
0    Banks  Moravian Falls    NC  36.0788  -81.1781    3495.0  1988-03-09   
1     Gill          Orient    WA  48.8878 -118.2105     149.0  1978-06-21   
2  Sanchez      Malad City    ID  42.1808 -112.2620    4154.0  1962-01-19   
3    White         Boulder    MT  46.2306 -112.1138    1939.0  1967-01-12   
4   Garcia        Doe Hill    VA  38.4207  -79.4629      99.0  1986-03-28   

   merch_lat  merch_long  is_fraud  
0  36.011293  -82.048315       0.0  
1  49.159047 -118.186462       0.0  
2  43.150704 -112.154481       0.0  
3  47.034331 -112.561071       0.0  
4  38.674999  -78.632459       0.0

In [11]:
fd.duplicated().sum()

0

In [14]:
fd.shape[0]

54491

In [15]:
fd.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54491 entries, 0 to 31123
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   trans_date_trans_time  54491 non-null  object 
 1   cc_num                 54491 non-null  float64
 2   category               54491 non-null  object 
 3   amt                    54491 non-null  float64
 4   first                  54491 non-null  object 
 5   last                   54491 non-null  object 
 6   city                   54491 non-null  object 
 7   state                  54491 non-null  object 
 8   lat                    54491 non-null  float64
 9   long                   54491 non-null  float64
 10  city_pop               54491 non-null  float64
 11  dob                    54491 non-null  object 
 12  merch_lat              54491 non-null  float64
 13  merch_long             54491 non-null  float64
 14  is_fraud               54491 non-null  float64
dtypes: floa

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

columns = ['trans_date_trans_time','category','first','last','city','state','lat','long','dob','merch_lat','merch_long']
for col in columns:

    if fd[col].apply(type).nunique() > 1:
        fd[col] = fd[col].astype(str)
    fd[col] = le.fit_transform(fd[col])

In [17]:
fd.head()

trans_date_trans_time        cc_num  category     amt  first  last  city  \
0                      0  2.703186e+15         9    4.97    154    19   494   
1                      1  6.304233e+11         5  107.23    297   156   569   
2                      2  3.885949e+13         1  220.11    107   374   440   
3                      3  3.534094e+15         3   45.00    155   449    82   
4                      4  3.755342e+14        10   41.96    323   148   204   

   state  lat  long  city_pop  dob  merch_lat  merch_long  is_fraud  
0     27  269   645    3495.0  722      16803       36646       0.0  
1     47  895    54     149.0  550      54123        3185       0.0  
2     13  679    79    4154.0  265      45294        4951       0.0  
3     26  864    82    1939.0  345      52693        4801       0.0  
4     45  365   700      99.0  677      24122       43680       0.0

In [18]:
x_train = fd.drop(columns=['is_fraud'])
y_train = fd['is_fraud']

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.2)

In [20]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [21]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=40)

In [22]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)


DecisionTreeClassifier()

In [23]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(x_train,y_train)

SVC()

In [24]:
lr.score(x_test,y_test)

0.9934856408844848

In [25]:
rf.score(x_test,y_test)

0.9977979631158822

In [26]:
dt.score(x_test,y_test)

0.9967886962106616

In [27]:
svm.score(x_test,y_test)

0.9934856408844848

In [28]:
y_predictlr = lr.predict(x_test)
y_predictlr

array([0., 0., 0., ..., 0., 0., 0.])

In [29]:
y_predictrf = rf.predict(x_test)
y_predictrf

array([0., 1., 0., ..., 0., 0., 0.])

In [30]:
y_predictdt = dt.predict(x_test)
y_predictdt

array([0., 1., 0., ..., 0., 0., 0.])

In [31]:
y_predictsvm = svm.predict(x_test)
y_predictsvm

array([0., 0., 0., ..., 0., 0., 0.])

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm1 = confusion_matrix(y_test, y_predictlr)
cm2 = confusion_matrix(y_test, y_predictrf)
cm3 = confusion_matrix(y_test, y_predictdt)
cm4 = confusion_matrix(y_test, y_predictsvm)

In [33]:
cm1_accuracy = accuracy_score(y_test, y_predictlr)
cm2_accuracy = accuracy_score(y_test, y_predictrf)
cm3_accuracy = accuracy_score(y_test, y_predictdt)
cm4_accuracy = accuracy_score(y_test, y_predictsvm)

In [34]:
print(cm1_accuracy)
print(cm2_accuracy)
print(cm3_accuracy)
print(cm4_accuracy)


0.9934856408844848
0.9977979631158822
0.9967886962106616
0.9934856408844848


In [35]:
print(cm1)
print(cm2)
print(cm3)
print(cm4)

[[10828     0]
 [   71     0]]
[[10828     0]
 [   24    47]]
[[10812    16]
 [   19    52]]
[[10828     0]
 [   71     0]]


In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predictlr))

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     10828
         1.0       0.00      0.00      0.00        71

    accuracy                           0.99     10899
   macro avg       0.50      0.50      0.50     10899
weighted avg       0.99      0.99      0.99     10899



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [37]:
print(classification_report(y_test, y_predictrf))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     10828
         1.0       1.00      0.66      0.80        71

    accuracy                           1.00     10899
   macro avg       1.00      0.83      0.90     10899
weighted avg       1.00      1.00      1.00     10899



In [38]:
print(classification_report(y_test, y_predictdt))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     10828
         1.0       0.76      0.73      0.75        71

    accuracy                           1.00     10899
   macro avg       0.88      0.87      0.87     10899
weighted avg       1.00      1.00      1.00     10899



In [39]:
print(classification_report(y_test, y_predictsvm))

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     10828
         1.0       0.00      0.00      0.00        71

    accuracy                           0.99     10899
   macro avg       0.50      0.50      0.50     10899
weighted avg       0.99      0.99      0.99     10899



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [40]:
Accuracy = pd.DataFrame({'logistic Regression':[cm1_accuracy],'RandomForest': [cm2_accuracy],'DecisionTree':[cm3_accuracy],'SVC': [cm4_accuracy]},index=['Accuracy'])
Accuracy

logistic Regression  RandomForest  DecisionTree       SVC
Accuracy             0.993486      0.997798      0.996789  0.993486