In [72]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [73]:
fraudtest_data = pd.read_csv('fraudTrain.csv')
fraudtest_data.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095   
1           1   2019-01-01 00:00:44      630423337322   
2           2   2019-01-01 00:00:51    38859492057661   
3           3   2019-01-01 00:01:16  3534093764340240   
4           4   2019-01-01 00:03:06   375534208663984   

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer   
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie   
2                fraud_Lind-Buckridge  entertainment  220.11     Edward   
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy   
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler   

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781   
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105   
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620   
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138   
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629   

   city_pop                                job         dob  \
0      3495          Psychologist, counselling  1988-03-09   
1       149  Special educational needs teacher  1978-06-21   
2      4154        Nature conservation officer  1962-01-19   
3      1939                    Patent attorney  1967-01-12   
4        99     Dance movement psychotherapist  1986-03-28   

                          trans_num     unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1.325376e+09  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1.325376e+09  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1.325376e+09  43.150704 -112.154481   
3  6b849c168bdad6f867558c3793159a81  1.325376e+09  47.034331 -112.561071   
4  a41d7549acf90789359a9aa5346dcb46  1.325376e+09  38.674999  -78.632459   

   is_fraud  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 23 columns]

In [74]:
fraudtrain_data = pd.read_csv('fraudTrain.csv')
fraudtrain_data.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095   
1           1   2019-01-01 00:00:44      630423337322   
2           2   2019-01-01 00:00:51    38859492057661   
3           3   2019-01-01 00:01:16  3534093764340240   
4           4   2019-01-01 00:03:06   375534208663984   

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer   
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie   
2                fraud_Lind-Buckridge  entertainment  220.11     Edward   
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy   
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler   

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781   
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105   
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620   
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138   
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629   

   city_pop                                job         dob  \
0      3495          Psychologist, counselling  1988-03-09   
1       149  Special educational needs teacher  1978-06-21   
2      4154        Nature conservation officer  1962-01-19   
3      1939                    Patent attorney  1967-01-12   
4        99     Dance movement psychotherapist  1986-03-28   

                          trans_num     unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1.325376e+09  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1.325376e+09  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1.325376e+09  43.150704 -112.154481   
3  6b849c168bdad6f867558c3793159a81  1.325376e+09  47.034331 -112.561071   
4  a41d7549acf90789359a9aa5346dcb46  1.325376e+09  38.674999  -78.632459   

   is_fraud  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 23 columns]

In [75]:
fraudtrain_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209573 entries, 0 to 209572
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Unnamed: 0             209573 non-null  int64  
 1   trans_date_trans_time  209573 non-null  object 
 2   cc_num                 209573 non-null  int64  
 3   merchant               209573 non-null  object 
 4   category               209573 non-null  object 
 5   amt                    209573 non-null  float64
 6   first                  209573 non-null  object 
 7   last                   209573 non-null  object 
 8   gender                 209573 non-null  object 
 9   street                 209573 non-null  object 
 10  city                   209573 non-null  object 
 11  state                  209573 non-null  object 
 12  zip                    209573 non-null  int64  
 13  lat                    209573 non-null  float64
 14  long                   209573 non-nu

In [76]:
fraudtest_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209573 entries, 0 to 209572
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Unnamed: 0             209573 non-null  int64  
 1   trans_date_trans_time  209573 non-null  object 
 2   cc_num                 209573 non-null  int64  
 3   merchant               209573 non-null  object 
 4   category               209573 non-null  object 
 5   amt                    209573 non-null  float64
 6   first                  209573 non-null  object 
 7   last                   209573 non-null  object 
 8   gender                 209573 non-null  object 
 9   street                 209573 non-null  object 
 10  city                   209573 non-null  object 
 11  state                  209573 non-null  object 
 12  zip                    209573 non-null  int64  
 13  lat                    209573 non-null  float64
 14  long                   209573 non-nu

In [77]:
fd = pd.concat([fraudtrain_data, fraudtest_data])
fd.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2019-01-01 00:00:18  2703186189652095   
1           1   2019-01-01 00:00:44      630423337322   
2           2   2019-01-01 00:00:51    38859492057661   
3           3   2019-01-01 00:01:16  3534093764340240   
4           4   2019-01-01 00:03:06   375534208663984   

                             merchant       category     amt      first  \
0          fraud_Rippin, Kub and Mann       misc_net    4.97   Jennifer   
1     fraud_Heller, Gutmann and Zieme    grocery_pos  107.23  Stephanie   
2                fraud_Lind-Buckridge  entertainment  220.11     Edward   
3  fraud_Kutch, Hermiston and Farrell  gas_transport   45.00     Jeremy   
4                 fraud_Keeling-Crist       misc_pos   41.96      Tyler   

      last gender                        street  ...      lat      long  \
0    Banks      F                561 Perry Cove  ...  36.0788  -81.1781   
1     Gill      F  43039 Riley Greens Suite 393  ...  48.8878 -118.2105   
2  Sanchez      M      594 White Dale Suite 530  ...  42.1808 -112.2620   
3    White      M   9443 Cynthia Court Apt. 038  ...  46.2306 -112.1138   
4   Garcia      M              408 Bradley Rest  ...  38.4207  -79.4629   

   city_pop                                job         dob  \
0      3495          Psychologist, counselling  1988-03-09   
1       149  Special educational needs teacher  1978-06-21   
2      4154        Nature conservation officer  1962-01-19   
3      1939                    Patent attorney  1967-01-12   
4        99     Dance movement psychotherapist  1986-03-28   

                          trans_num     unix_time  merch_lat  merch_long  \
0  0b242abb623afc578575680df30655b9  1.325376e+09  36.011293  -82.048315   
1  1f76529f8574734946361c461b024d99  1.325376e+09  49.159047 -118.186462   
2  a1a22d70485983eac12b5b88dad1cf95  1.325376e+09  43.150704 -112.154481   
3  6b849c168bdad6f867558c3793159a81  1.325376e+09  47.034331 -112.561071   
4  a41d7549acf90789359a9aa5346dcb46  1.325376e+09  38.674999  -78.632459   

   is_fraud  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 23 columns]

In [78]:
fd.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                2
merch_lat                2
merch_long               2
is_fraud                 2
dtype: int64

In [79]:
fd.shape[0]

419146

In [80]:
fd.fillna(0, inplace=True)
fd.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [81]:
fd.drop(columns=['Unnamed: 0', 'gender', 'street', 'job', 'unix_time','trans_num','merchant','zip'], inplace=True)
fd.head()

trans_date_trans_time            cc_num       category     amt      first  \
0   2019-01-01 00:00:18  2703186189652095       misc_net    4.97   Jennifer   
1   2019-01-01 00:00:44      630423337322    grocery_pos  107.23  Stephanie   
2   2019-01-01 00:00:51    38859492057661  entertainment  220.11     Edward   
3   2019-01-01 00:01:16  3534093764340240  gas_transport   45.00     Jeremy   
4   2019-01-01 00:03:06   375534208663984       misc_pos   41.96      Tyler   

      last            city state      lat      long  city_pop         dob  \
0    Banks  Moravian Falls    NC  36.0788  -81.1781      3495  1988-03-09   
1     Gill          Orient    WA  48.8878 -118.2105       149  1978-06-21   
2  Sanchez      Malad City    ID  42.1808 -112.2620      4154  1962-01-19   
3    White         Boulder    MT  46.2306 -112.1138      1939  1967-01-12   
4   Garcia        Doe Hill    VA  38.4207  -79.4629        99  1986-03-28   

   merch_lat  merch_long  is_fraud  
0  36.011293  -82.048315       0.0  
1  49.159047 -118.186462       0.0  
2  43.150704 -112.154481       0.0  
3  47.034331 -112.561071       0.0  
4  38.674999  -78.632459       0.0

In [82]:
fd.duplicated().sum()

209573

In [83]:
fd.drop_duplicates(inplace=True)
fd.duplicated().sum()

0

In [84]:
fd.shape[0]

209573

In [85]:
fd.info()

<class 'pandas.core.frame.DataFrame'>
Index: 209573 entries, 0 to 209572
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   trans_date_trans_time  209573 non-null  object 
 1   cc_num                 209573 non-null  int64  
 2   category               209573 non-null  object 
 3   amt                    209573 non-null  float64
 4   first                  209573 non-null  object 
 5   last                   209573 non-null  object 
 6   city                   209573 non-null  object 
 7   state                  209573 non-null  object 
 8   lat                    209573 non-null  float64
 9   long                   209573 non-null  float64
 10  city_pop               209573 non-null  int64  
 11  dob                    209573 non-null  object 
 12  merch_lat              209573 non-null  float64
 13  merch_long             209573 non-null  float64
 14  is_fraud               209573 non-null  f

In [86]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

columns = ['trans_date_trans_time','category','first','last','city','state','lat','long','dob','merch_lat','merch_long']
for col in columns:

    if fd[col].apply(type).nunique() > 1:
        fd[col] = fd[col].astype(str)
    fd[col] = le.fit_transform(fd[col])

In [87]:
fd.head()

trans_date_trans_time            cc_num  category     amt  first  last  \
0                      0  2703186189652095         8    4.97    155    18   
1                      1      630423337322         4  107.23    299   155   
2                      2    38859492057661         0  220.11    108   376   
3                      3  3534093764340240         2   45.00    156   453   
4                      4   375534208663984         9   41.96    325   147   

   city  state  lat  long  city_pop  dob  merch_lat  merch_long  is_fraud  
0   506     26  274   663      3495  736      64315      140964       0.0  
1   583     46  915    57       149  564     207269       12655       0.0  
2   452     12  695    83      4154  271     173128       19256       0.0  
3    82     25  883    86      1939  357     201787       18709       0.0  
4   209     44  374   719        99  691      92523      168240       0.0

In [88]:
x_train = fd.drop(columns=['is_fraud'])
y_train = fd['is_fraud']

In [89]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.2)

In [90]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [110]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=40)

In [91]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)


DecisionTreeClassifier()

In [92]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(x_train,y_train)

SVC()

In [93]:
lr.score(x_test,y_test)

0.9926995109149469

In [111]:
rf.score(x_test,y_test)

0.9973040677561732

In [95]:
dt.score(x_test,y_test)

0.9949898604318264

In [96]:
svm.score(x_test,y_test)

0.9926995109149469

In [97]:
y_predictlr = lr.predict(x_test)
y_predictlr

array([0., 0., 0., ..., 0., 0., 0.])

In [112]:
y_predictrf = rf.predict(x_test)
y_predictrf

array([0., 0., 0., ..., 0., 0., 0.])

In [99]:
y_predictdt = dt.predict(x_test)
y_predictdt

array([0., 0., 0., ..., 0., 0., 0.])

In [100]:
y_predictsvm = svm.predict(x_test)
y_predictsvm

array([0., 0., 0., ..., 0., 0., 0.])

In [113]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm1 = confusion_matrix(y_test, y_predictlr)
cm2 = confusion_matrix(y_test, y_predictrf)
cm3 = confusion_matrix(y_test, y_predictdt)
cm4 = confusion_matrix(y_test, y_predictsvm)

In [114]:
cm1_accuracy = accuracy_score(y_test, y_predictlr)
cm2_accuracy = accuracy_score(y_test, y_predictrf)
cm3_accuracy = accuracy_score(y_test, y_predictdt)
cm4_accuracy = accuracy_score(y_test, y_predictsvm)

In [115]:
print(cm1_accuracy)
print(cm2_accuracy)
print(cm3_accuracy)
print(cm4_accuracy)


0.9926995109149469
0.9973040677561732
0.9949898604318264
0.9926995109149469


In [116]:
print(cm1)
print(cm2)
print(cm3)
print(cm4)

[[41609     0]
 [  306     0]]
[[41595    14]
 [   99   207]]
[[41496   113]
 [   97   209]]
[[41609     0]
 [  306     0]]


In [117]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predictlr))

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     41609
         1.0       0.00      0.00      0.00       306

    accuracy                           0.99     41915
   macro avg       0.50      0.50      0.50     41915
weighted avg       0.99      0.99      0.99     41915



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [118]:
print(classification_report(y_test, y_predictrf))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     41609
         1.0       0.94      0.68      0.79       306

    accuracy                           1.00     41915
   macro avg       0.97      0.84      0.89     41915
weighted avg       1.00      1.00      1.00     41915



In [119]:
print(classification_report(y_test, y_predictdt))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     41609
         1.0       0.65      0.68      0.67       306

    accuracy                           0.99     41915
   macro avg       0.82      0.84      0.83     41915
weighted avg       1.00      0.99      1.00     41915



In [120]:
print(classification_report(y_test, y_predictsvm))

              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     41609
         1.0       0.00      0.00      0.00       306

    accuracy                           0.99     41915
   macro avg       0.50      0.50      0.50     41915
weighted avg       0.99      0.99      0.99     41915



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [121]:
Accuracy = pd.DataFrame({'logistic Regression':[cm1_accuracy],'RandomForest': [cm2_accuracy],'DecisionTree':[cm3_accuracy],'SVC': [cm4_accuracy]},index=['Accuracy'])
Accuracy

logistic Regression  RandomForest  DecisionTree     SVC
Accuracy               0.9927      0.997304       0.99499  0.9927